### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by upaternostro**
Sorry, #7 is buggy (my fault). @vchepkov suggested a fix in #8, I think this is simpler

### CODE REVIEW

**Comment by djjudas21** [comment]
Thanks, I agree that this is simpler. I wonder if there are any cases where this solution breaks, e.g. when using Hiera. I'll accept this for now and we can always reconsider later.

**Comment by upaternostro** [comment]
Well, I do use Hiera in my infrastructure. It is as simple as adding a quote ;)

`apcupsd::service_ensure: 'stopped'`
`apcupsd::service_enable: 'false'`

Moreover, as in the docs ([https://puppet.com/docs/puppet/5.4/types/service.html#service-attribute-enable](url)) it doesn't clearly state if boolean values are allowed, I preferred to play it safe. Please reconsider if you like.

**Comment by vchepkov** [comment]
Are you planning to release a new version with the fix?
Furthermore, would you be open to a refactoring using modern 'data-in-module' approach?
I can create a PR

**Comment by djjudas21** [comment]
Yes, I can release a new version today.

Personally I no longer use this module but if you can create a PR with the changes then I will review and accept it - thanks.

**Comment by djjudas21** [comment]
I've just tagged and published `1.1.1`

**Pull request merged**
