### PR TITLE
add parameters to configure nis server

### PR DESCRIPTION
**Pull request by XnS**
allow configuration of nis server settings

### CODE REVIEW

**Comment by djjudas21** [comment]
Hey, thanks for your contribution - sorry i took a while to reply. Please could you add your new parameters to `README.md` and then I'l be happy to accept :+1:

**Comment by XnS** [comment]
Hi @djjudas21,
updated README and adapted to the latest state.

Regards,
~X

**Comment by djjudas21** [comment]
Great, thanks!

**Comment by XnS** [comment]
No problem. Do you plan to release a new version for puppetforge soon?

**Comment by djjudas21** [comment]
Yes, I'll tag a release now

**Comment by djjudas21** [comment]
All done, v1.0.1 is ready for you

**Comment by XnS** [comment]
Thank you very much.

**Pull request merged**
